blog/urls.py
from django.urls import path

from blog import views

app_name = "blog"


urlpatterns = [
    path("", views.BlogListView.as_view(), name="list"),
]

cultch/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

from .views import HomePageView, GameView
from .translations import set_language

urlpatterns = [
    path('management/', admin.site.urls),
    path('setlang/', set_language, name='set_language'),
    path('', GameView.as_view(), name='game'),

]

# Language Translation
urlpatterns += i18n_patterns(
    path('', HomePageView.as_view(), name='home'),
    path('user/', include('customauth.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('courses/', include('course.urls')),
    path('blogs/', include('blog.urls')),
    path('virtualtour/', include('virtualtour.urls')),
    path('history/', include('history.urls')),
    path('readclassic/', include('readclassic.urls')),
    path('diago/', include('diago.urls')),
    path('west/', include('west.urls')),

)

# rosetta urls ------------------------------
if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

# serve media files in development environment --------------------------------
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

readclassic/urls.py
from django.urls import path

from course import views
from readclassic import views

app_name = "readclassic"


urlpatterns = [
    path("<email>/", views.ClassicsharingPagegameView.as_view(), name="cs"),
    path('lfs/', views.LearnFamousPagesongsView.as_view(), name="lfs"),
    path(
        '<int:id>/sdetails/', views.SharingDetailsView.as_view(),
        name='sdetails'
        ),
    path(
        '<int:id>/<int:likes>/sdetailsa/', views.SharingDetails_saveView.as_view(),
        name='sdetailsup'
    ),
    path(
        '<int:id>/<int:classicid>/sdetails/', views.SharingDetails_delete_commentView.as_view(),
        name='sdetailsde'
    ),
    path(
        '<int:id>/<email>/sdetailsb/', views.SharingDetails_delete_classicView.as_view(),
        name='sdetaildeclassic'
    ),

]

readclassic/models.py
from django.db import models
class Classic(models.Model):
    id=models.BigIntegerField(primary_key=True)
    title = models.CharField(max_length=255)
    content = models.TextField()
    create_time = models.CharField(max_length=255)
    category =models.CharField(max_length=255)
    author=models.CharField(max_length=255,default='1827316887@qq.com')
    likes=models.BigIntegerField(default=0)
    img = models.ImageField(upload_to='images', default='avatar-2024033113040001029.jpg')  # 本次使用的是这个
    class Meta:
        db_table = 'classic'



class Comment(models.Model):
    id=models.BigIntegerField(primary_key=True)
    content = models.TextField()
    comment_time = models.CharField(max_length=255)
    pre_id =models.BigIntegerField()

    author_email=models.CharField(max_length=255,default='1827316887@qq.com')
    classicid=models.BigIntegerField()

    class Meta:
        db_table = 'comment'

readclassic/views.py
import os
import time
from datetime import datetime
from random import random
import numpy as np
from django.core.files.base import ContentFile
from django.core.files.storage import default_storage
from django.db.models import Count, Q
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import View, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404

from course.models import Course, CourseContent, CourseContentReadStatus
from cultch import settings
from readclassic import models
from readclassic.models import Classic, Comment


class ClassicsharingPagegameView(View):
    """ game view """
    template_name = 'readclassic/Classic_Sharing.html'

    def get(self, request, *args, **kwargs):
        obj = models.Comment.objects.filter(author_email=self.kwargs['email']).values('classicid')
        ob_ca=models.Classic.objects.filter(id__in= obj).values('category')
        print(ob_ca)
        classics = Classic.objects.all()
        classics_proposed = Classic.objects.filter(category__in= ob_ca)
        return render(request, self.template_name, {'classics': classics,'c_pr':classics_proposed})


    def post(self, request, *args, **kwargs):
        img_obj = request.FILES.get('img')
        # 保存文件
        new_name = getNewName('avatar')  # 具体实现在自己写的uploads.py下
        # 将要保存的地址和文件名称
        where = '%s/images/%s' % (settings.MEDIA_ROOT, new_name)
        # 分块保存image
        content = img_obj.chunks()
        with open(where, 'wb') as f:
            for i in content:
                f.write(i)
        author = request.POST.get('author')
        content = request.POST.get('content')
        title = request.POST.get('title')
        current_datetime = datetime.now()
        create_time = current_datetime.strftime("%Y-%m-%d %H:%M:%S")
        ca=request.POST.get('category')
        Classic.objects.create(title=title,content=content,create_time=create_time,category=ca,author=author,img=new_name)
        obj = models.Comment.objects.filter(author_email=self.kwargs['email']).values('classicid')
        ob_ca=models.Classic.objects.filter(id__in= obj).values('category')
        print(ob_ca)
        classics = Classic.objects.all()
        classics_proposed = Classic.objects.filter(category__in= ob_ca)
        return render(request, self.template_name, {'classics': classics,'c_pr':classics_proposed})


class LearnFamousPagesongsView(View):
    """ s view """
    template_name = 'readclassic/Learn_Famous_Sayings.html'

    def get(self, request, *args, **kwargs):

        return render(request, self.template_name)




class SharingDetailsView(View):
    template_name = 'readclassic/class_sharing_details.html'

    def get(self, request, *args, **kwargs):
        # 根据ID查询c
        comment_list = Comment.objects.filter(classicid=self.kwargs['id'])
        c =get_object_or_404(Classic, id=self.kwargs['id'])
        context = {
                'classic': c,
                'comment_list':comment_list
            }
        print(comment_list)
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
            email = request.POST.get('email_pcd')
            print("email",email)
            content = request.POST.get('content')
            classicid = request.POST.get('classicid')
            current_datetime = datetime.now()
            comment_time = current_datetime.strftime("%Y-%m-%d %H:%M:%S")
            Comment.objects.create(content=content,classicid=classicid,author_email=email,comment_time=comment_time)
            comment_list = Comment.objects.filter(classicid=self.kwargs['id'])
            print(comment_list)
            c = get_object_or_404(Classic, id=self.kwargs['id'])
            context = {
                'classic': c,
                'comment_list': comment_list
            }
            return render(request, self.template_name, context)
class SharingDetails_saveView(View):
    template_name = 'readclassic/class_sharing_details.html'

    def get(self, request, *args, **kwargs):
        # ID_>c
        Classic.objects.filter(id=self.kwargs['id']).update(likes=int(self.kwargs['likes'])+1)
        c = get_object_or_404(Classic, id=self.kwargs['id'])
        comment_list = Comment.objects.filter(classicid=self.kwargs['id'])
        print(comment_list)
        context = {
        'classic': c,
        'comment_list': comment_list
         }
        return render(request, self.template_name,context)


    def post(self, request, *args, **kwargs):

        email = request.POST.get('email_pcd')
        print("email1", email)
        content = request.POST.get('content')
        classicid = request.POST.get('classicid')
        current_datetime = datetime.now()
        comment_time = current_datetime.strftime("%Y-%m-%d %H:%M:%S")
        Comment.objects.create(content=content, classicid=classicid, author_email=email, comment_time=comment_time)
        comment_list = Comment.objects.filter(classicid=self.kwargs['id'])
        c = get_object_or_404(Classic, id=self.kwargs['id'])
        print(comment_list)
        context = {
            'comment_list': comment_list,
        'classic': c,
        }
        return render(request, self.template_name,context)

def getNewName(file_type):
     #this function is update image name
        new_name = time.strftime(file_type + '-%Y%m%d%H%M%S', time.localtime())
        ranlist = np.random.randint(0, 10, 5)
        for i in ranlist:
            new_name += str(i)
        new_name += '.jpg'
        return new_name

class SharingDetails_delete_commentView(View):
    template_name = 'readclassic/class_sharing_details.html'

    def get(self, request, *args, **kwargs):
        # ID_>c
        Comment.objects.filter(id=self.kwargs['id']).delete()
        c = get_object_or_404(Classic, id=self.kwargs['classicid'])
        comment_list = Comment.objects.filter(classicid=self.kwargs['classicid'])
        print(comment_list)
        context = {
        'classic': c,
        'comment_list': comment_list
         }
        return render(request, self.template_name,context)
class SharingDetails_delete_classicView(View):
    template_name = 'readclassic/Classic_Sharing.html'

    def get(self, request, *args, **kwargs):
        # 根据ID查询c
        Classic.objects.filter(id=self.kwargs['id']).delete()
        classics = Classic.objects.all()
        obj = models.Comment.objects.filter(author_email=self.kwargs['email']).values('classicid')
        ob_ca = models.Classic.objects.filter(id__in=obj).values('category')
        print(ob_ca)

        classics_proposed = Classic.objects.filter(category__in=ob_ca)

        context = {
                'classics': classics,
                 'c_pr': classics_proposed
            }
        return render(request, self.template_name, context)

templates/readclassic/Classic_Sharing.html
{% extends 'base/base.html' %}
{% load humanize static i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
{% load static %}
{% load static i18n %}
{% block content %}
<div class="container" style="background-image: url('/static/images/bg.jpg')">
<p>
    <span style="
     text-align: center;
     padding-bottom: 6px;
     padding-left: 10px;
     padding-right: 70%;
     color: rgba(6,53,180,0.56);
     padding-top: -30px;
     margin-top: -400px;
     box-shadow: 10px 10px 5px rgba(136,136,136,0.12);"
    ><strong> <span style="font-size: 18px;"><img src="/static/images/icon103.png" width="30px" height="30px" style="background-image: url('/static/images/bg.jpg')">{% translate 'Share List' %}</span></strong></span></p>
   <table class="table11_7">
           <tr>
        <th>{% translate 'id' %}</th><th>{% translate 'source' %}</th><th>{% translate 'category' %}</th><th>{% translate ' sharing author' %}</th><th>{% translate 'time' %}</th><th>{% translate 'operation' %}</th>
    </tr>
            {% for classic in classics %}
       <tr>
           <td>{{ classic.id }}</td>
           <td>{{ classic.title }}</td>
           <td>{{ classic.category }}</td>
           <td>{{ classic.author}}</td>
           <td>{{ classic.create_time}}</td>
           <td>

           <a href="{% url 'readclassic:sdetails' classic.id %}">查看详情</a>
            {% if  classic.author == user.email  %}
                <a href="{% url 'readclassic:sdetaildeclassic' classic.id user.email%}">删除</a>
               {% endif %}
           </td>


       </tr>
        {% endfor %}
   </table>

<br/>
<p>
    <span style="
     text-align: center;
     padding-bottom: 6px;
     padding-left: 10px;
     padding-right: 70%;
     color: rgba(6,53,180,0.56);
     padding-top: -30px;
     margin-top: 300px;
     box-shadow: 10px 10px 5px rgba(136,136,136,0.12);"
    ><strong> <span style="font-size: 18px;"><img src="/static/images/icon103.png" width="30px" height="30px" style="background-image: url('/static/images/bg.jpg')">{% translate 'Share Time' %}</span></strong></span></p>
  <form action="{% url 'readclassic:cs' user.email %}" method="post" class="basic-grey" enctype="multipart/form-data">

    <h1>Share Form
        <span>Please share classic books that you read in here.</span>
    </h1>
      {% csrf_token %}

    <label>
        <span>Title :</span>
        <textarea id="message" name="title" placeholder="Your Content to Classic">   </textarea>
    </label>
    <label>
        <span>Content :</span>
        <textarea id="message" name="content" placeholder="Your Content to Classic">   </textarea>
    </label>

    <label>

        <input id="name" type="text" name="author"  value="{{ user.email }}" hidden="hidden"/>
    </label>
 <label>
        <span>Category :</span>
     <select name="category">
         <option value="哲学">哲学</option>
           <option value="历史">历史</option>
             <option value="文学">文学</option>
              <option value="文学">旅游</option>
           <option value="文学">其他</option>
     </select>
    </label>
    <label>
        <span>Image :</span>
           <input type="file" name="img">
        <p style="font-size: 10px;color: red">{% translate 'Note: Only support (.jpeg|.jpg|.bmp|.png) type' %}</p>

    </label>
    <label>
        <input type="submit" class="button1" value="Share this" />

    </label>
</form>
<p>
    <span style="
     text-align: center;
     padding-bottom: 6px;
     padding-left: 10px;
     padding-right: 70%;
     color: rgba(6,53,180,0.56);
     padding-top: -30px;
     margin-top: 300px;
     box-shadow: 10px 10px 5px rgba(136,136,136,0.12);"
    ><strong> <span style="font-size: 18px;"><img src="/static/images/icon103.png" width="30px" height="30px" style="background-image: url('/static/images/bg.jpg')">{% translate 'Guess You Like' %}</span></strong></span></p>
<div>
  {% if c_pr %}
      <table class="table11_7">
           <tr>
        <th>{% translate 'id' %}</th><th>{% translate 'source' %}</th><th>{% translate 'category' %}</th><th>{% translate ' sharing author' %}</th><th>{% translate 'time' %}</th><th>{% translate 'operation' %}</th>
    </tr>
            {% for classic1 in c_pr %}
       <tr>
           <td>{{ classic1.id }}</td>
           <td>{{ classic1.title }}</td>
           <td>{{ classic1.category }}</td>
           <td>{{ classic1.author}}</td>
           <td>{{ classic1.create_time}}</td>
           <td>

           <a href="{% url 'readclassic:sdetails' classic1.id %}">查看详情</a>
            {% if  classic1.author == user.email  %}
                <a href="{% url 'readclassic:sdetaildeclassic' classic1.id user.email %}">删除</a>
               {% endif %}
           </td>


       </tr>
        {% endfor %}
   </table>

{% else %}
      <p style="color: #c6c8ca;font-size: 10px;margin-top: 4%">{% translate 'We have not Something to recommend to you, please comment more' %}</p>
   {% endif %}


</div>
</div>
    <style>
    .table11_7 {
        width:100%;
        margin:0 3%;
        border:0;
    }
    .table11_7 th {
        background-color:#00A5FF;
        color:#FFFFFF
    }
    .table11_7,.table11_7 th,.table11_7 td {
        font-size:0.95em;
        text-align:center;
        padding:4px;
        border-collapse:collapse;
    }
    .table11_7 th,.table11_7 td {
        border: 1px solid rgba(19, 110, 199, 0.57);
        border-width:1px 0 1px 0;
        border:2px inset #ffffff;
    }
    .table11_7 tr {
        border: 1px solid #ffffff;
    }
    .table11_7 tr:nth-child(odd){
        background-color:#aae1fe;
    }
    .table11_7 tr:nth-child(even){
        background-color:#ffffff;
    }
</style>

{% endblock content %}

templates/readclassic/class_sharing_details.html
{% extends 'base/base.html' %}
{% load static %}
{% load static i18n %}
{% block content %}<body style="background-image: url('/static/images/bg.jpg')">
<div class="container" >

<link href="/static/css/style34.css" rel="stylesheet" type="text/css" media="all" />
<link href="/static/css/form1.css" rel="stylesheet" type="text/css" media="all" />
<link href='http//fonts.googleapis.com/css?family=Exo+2' rel='stylesheet' type='text/css'>
<script src="/static/js/jquery1.min.js"></script>
<!-- start menu -->
<link href="/static/css/megamenu1.css" rel="stylesheet" type="text/css" media="all" />
<script type="text/javascript" src="/static/js/megamenu.js"></script>
<script>$(document).ready(function(){$(".megamenu").megamenu();});</script>
<script type="text/javascript" src="/static/js/jquery.jscrollpane.min.js"></script>
		<script type="text/javascript" id="sourcecode">
			$(function()
			{
				$('.scroll-pane').jScrollPane();
			});
		</script>
<!-- start details -->
<script src="/static/js/slides.min.jquery.js"></script>
   <script>
		$(function(){
			$('#products').slides({
				preload: true,
				preloadImage: '/static/images/loading.gif',
				effect: 'slide, fade',
				crossfade: true,
				slideSpeed: 350,
				fadeSpeed: 500,
				generateNextPrev: true,
				generatePagination: false
			});
		});
	</script>
	<!-- start zoom -->
	<link rel="stylesheet" href="/static/css/zoome-min1.css" />
	<script type="text/javascript" src="/static/js/zoome-e.js"></script>
	<script type="text/javascript">
		$(function(){
		$('#img1,#img2,#img3,#img4').zoome({showZoomState:true,magnifierSize:[250,250]});
	});
	</script>
<style>
    ul{font-size: 20px}

</style>
  <div class="main1">
     <div class="wrap">
     	<ul class="breadcrumb breadcrumb__t"><i class="ti-arrow-right"></i>&nbsp;&nbsp;<a class="home" href="{% url 'home' %}">Home</a> / <a href="{% url 'readclassic:cs'  user.email%}">{% translate 'Classic Sharing' %}</a> / {% translate 'Details' %}</ul>
		<div class="cont span_2_of_3">
		  	<div class="grid images_3_of_2">
						<div id="container">
							<div id="products_example">
								<div id="products">
									<ul class="pagination">
										<li> <img class="a" id="img1" src="/media/images/{{classic.img }}" alt=""  width="100%" height="100%"/></li>

									</ul>
								</div>
							</div>
						</div>
	            </div>
		         <div class="desc1 span_3_of_2">
                     <h3 class="m_3" style="font-weight: bolder">《{{ classic.title }}》<br> <span style="font-size: 10px">  <i class="ti-user mr-2"></i> {{ classic.author}}
					&emsp;<span class="m_link"> <i class="ti-time mr-2"></i><a href="#">{{ classic.create_time}}</a> </span>&emsp;<i class="ti-book mr-2"></i>{{ classic.category }}</span></h3>


				     <p class="m_text2" style="border: 1px dashed #c6c8ca">{{ classic.content}}</p><br>
                     <div style="border: 1px dashed #c6c8ca;text-align: right;border: none"><a href="{% url 'readclassic:sdetailsup' classic.id  classic.likes %}"><span class="mr1-2">{% translate 'like' %}</span></a>{{ classic.likes}}</div>
			     </div>
			   <div class="clear"></div>
	    <div class="clients">

	<script type="text/javascript" src="/static/js/jquery.flexisel.js"></script>
     </div>
     <div class="toogle">
{#     	<h3 class="m_3">{% translate 'Comment or Share' %}</h3>#}
     	<p class="m_text">
<style>
    .myahref

    {
        margin-left: 1%;

    }
     .myahref:hover

    {
       background-image: url("/static/images/rubbish.png");
         background-size: contain;
         background-repeat: no-repeat;
         color: transparent;
         z-index: 30;

    }
</style>
<div class="feedback_area_title">     <p>
    <span style="
     text-align: center;
     padding-bottom: 6px;
     padding-left: 10px;
     padding-right: 70%;
     color: rgba(6,53,180,0.56);
     padding-top: -30px;
     margin-top: -400px;
     box-shadow: 10px 10px 5px rgba(136,136,136,0.12);"
><strong> <span style="font-size: 18px;"><img src="/static/images/icon103.png" width="30px" height="30px" style="background-image: url('/static/images/bg.jpg')">{% translate 'Comment List' %}</span></strong></span></p></div>
        <div class="comment_list">
          {% if  comment_list %}
            {% for comment in comment_list %}

                <div class="cb" id="one">
                    <p><i class="ti-flag"></i>{{ forloop.counter}} &emsp;<i class="ti-user mr-2"></i>{{comment.author_email}}&emsp; <i class="ti-time mr-2"></i> {{ comment.comment_time}}    {% if  comment.author_email == user.email  %}
                    <a href="{% url 'readclassic:sdetailsde' comment.id classic.id %}" class="myahref ">{% translate 'delete' %}</a>
                {%endif%}
                    <br/><br/><br/><p style="margin-left: 10%;font-size: 20px;font-family: "Helvetica Neue", Helvetica, Arial, sans-serif"></i>{{comment.content}}</p>
                    <hr>

                </div>
               {% endfor %}
          {% else %}
                <p style="color: #c6c8ca;margin-top: 2%">{%  translate 'Have no comments now, you can give you comments' %}</p>
          {%endif%}

        </div>
        </p>
     </div>
     <div class="toogle">
 <p>
    <span style="
     text-align: center;
     padding-bottom: 6px;
     padding-left: 10px;
     padding-right: 70%;
     color: rgba(6,53,180,0.56);
     padding-top: -30px;
     margin-top: -400px;
     box-shadow: 10px 10px 5px rgba(136,136,136,0.12);"
><strong> <span style="font-size: 18px;"><img src="/static/images/icon103.png" width="30px" height="30px" style="background-image: url('/static/images/bg.jpg')">{% translate 'Comment and Share' %}</span></strong></span></p></div>
  <form action="{% url 'readclassic:sdetails' classic.id %}" method="post" class="basic-grey">

    <h1>Comment Form
        <span>Please give your comments on the classic.</span>
    </h1>
      {% csrf_token %}



    <label>
        <span>Content :</span>
        <textarea id="message" name="content" placeholder="Your Content to Classic">   </textarea>
    </label>
            <label>
    <label>

        <input id="name" type="text" name="email_pcd"  value="{{ user.email }}" hidden="hidden"/>
    </label>
        <input id="name" type="text" name="classicid"  value="{{ classic.id }}" hidden="hidden"/>
    </label>

    <label>
        <span>&nbsp;</span>
        <input type="submit" class="button" value="Comment" />
    </label>
</form>

     </div>
      </div>
			<div class="rsingle span_1_of_single">
				<h5 class="m_1">Categories</h5>

					<ul class="kids">
						<li><a href="#">哲学</a></li>
						<li class="last"><a href="#">文学</a></li>
                        		<li class="last"><a href="#">历史</a></li>
                        		<li class="last"><a href="#">旅游</a></li>
					</ul>
                   <section  class="sky-form">
					<h5 class="m_1">Popular</h5>

					<ul class="kids">
						<li><a href="#">哲学</a></li>
						<li class="last"><a href="#">文学</a></li>

					</ul>
                       <h5 class="m_1">Popular Sharings</h5>

					<ul class="kids">
						<li><a href="#">《论语》</a></li>
						<li class="last"><a href="#">《三字经》</a></li>

					</ul>
                    <h5 class="m_1">Popular Users</h5>

					<ul class="kids">
						<li><a href="#">1827316887@qq.com</a></li>
						<li class="last"><a href="#">wtsf.sdfqss@qq.com</a></li>

					</ul>
		       </section>
		       <script src="/static/js/jquery.easydropdown.js"></script>
		      </div>
		      <div class="clear"></div>
			</div>
			 <div class="clear"></div>
		   </div>
		</div>
</div>
    </body>
{% endblock content %}