blog/urls.py
from django.urls import path

from blog import views

app_name = "blog"


urlpatterns = [
    path("", views.BlogListView.as_view(), name="list"),
]

course/urls.py
from django.urls import path

from course import views

app_name = "course"


urlpatterns = [
    path("", views.CourseListView.as_view(), name="list"),
    path(
        '<int:pk>/details/', views.CourseDetailsView.as_view(),
        name='details'
    ),
    path(
        '<int:pk>/overview/', views.CourseOverviewView.as_view(),
        name='overview'
    ),
    path(
        '<int:pk>/content/', views.CourseContentView.as_view(),
        name='content'
    ),
]

cultch/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

from .views import HomePageView, GameView
from .translations import set_language

urlpatterns = [
    path('management/', admin.site.urls),
    path('setlang/', set_language, name='set_language'),
    path('', GameView.as_view(), name='game'),

]

# Language Translation
urlpatterns += i18n_patterns(
    path('', HomePageView.as_view(), name='home'),
    path('user/', include('customauth.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('courses/', include('course.urls')),
    path('blogs/', include('blog.urls')),
    path('virtualtour/', include('virtualtour.urls')),
    path('history/', include('history.urls')),
    path('readclassic/', include('readclassic.urls')),
    path('diago/', include('diago.urls')),
    path('west/', include('west.urls')),

)

# rosetta urls ------------------------------
if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

# serve media files in development environment --------------------------------
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

course/models.py
from django.db import models
from tinymce.models import HTMLField


class Course(models.Model):
    """ Course model """
    title = models.CharField(max_length=500)
    description = models.TextField()
    photo = models.ImageField(upload_to="course/")
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    @property
    def total_module(self):
        return self.course_module.all().count()


class CourseModule(models.Model):
    course = models.ForeignKey(
        Course, on_delete=models.CASCADE, related_name="course_module"
    )
    name = models.CharField(max_length=255)
    ordering = models.PositiveIntegerField()
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    @property
    def total_content(self):
        return self.course_content.all().count()


class CourseContent(models.Model):
    course_module = models.ForeignKey(
        CourseModule, on_delete=models.CASCADE, related_name="course_content"
    )
    name = models.CharField(max_length=255)
    content = HTMLField()
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    @property
    def read_status(self):
        content_read_status = CourseContentReadStatus.objects.get(content=self)
        return content_read_status.is_read


class CourseContentReadStatus(models.Model):
    user = models.ForeignKey(
        "customauth.User", on_delete=models.CASCADE,
        related_name="content_read_status"
    )
    content = models.ForeignKey(
        CourseContent, on_delete=models.CASCADE, related_name="content_read"
    )
    is_read = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user}"

course/views.py
from django.views.generic import View, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404

from course.models import Course, CourseContent, CourseContentReadStatus


class CourseListView(ListView):
    """ Course view """
    template_name = 'course/course.html'
    model = Course

    def get_queryset(self, **kwargs):
        self.course_list = self.model.objects.all().order_by('-pk')
        return self.course_list

    def get_context_data(self, **kwargs):
        context = super(CourseListView, self).get_context_data(**kwargs)
        context['total_count'] = self.course_list.count()
        return context


class CourseDetailsView(View):
    template_name = 'course/course-details.html'

    def get(self, request, *args, **kwargs):
        course = get_object_or_404(Course, pk=self.kwargs['pk'])
        context = {
            'course': course
        }
        return render(request, self.template_name, context)


class CourseOverviewView(LoginRequiredMixin, View):
    template_name = 'courses/overview.html'

    def get(self, request, *args, **kwargs):
        course = get_object_or_404(Course, pk=self.kwargs['pk'])
        context = {
            'course': course
        }
        return render(request, self.template_name, context)


class CourseContentView(LoginRequiredMixin, View):
    template_name = 'courses/learning.html'

    def get(self, request, *args, **kwargs):
        content = get_object_or_404(CourseContent, pk=self.kwargs['pk'])
        CourseContentReadStatus.objects.get_or_create(
            user=request.user,
            content=content,
            is_read=True
        )
        context = {
            'content': content,
            'course': content.course_module.course
        }
        return render(request, self.template_name, context)

templates/course/course.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
<div class="blog-page pt-lg--7 pb-lg--7 pt-5 pb-5">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 mb-4">
                <div class="card rounded-xxl p-lg--5 border-0 bg-no-repeat" style="background-color: #e4f7fe;">
                    <div class="card-body w-100 p-4">
                        <div class="form-group mt-3 p-3 border-light border p-2 bg-white rounded-lg">
                            <div class="row">
                                <div class="col-lg-5">
                                    <div class="form-group icon-input mb-0">
                                        <i class="ti-search font-xs text-grey-400"></i>
                                        <input type="text" class="style1-input border-0 pl-5 font-xsss mb-0 text-grey-500 fw-500 bg-transparent" placeholder="Search online courses.." />
                                    </div>
                                </div>

                                <div class="col-lg-4">
                                    <div class="form-group icon-input mb-0">
                                        <i class="ti-package font-xs text-grey-400"></i>
                                        <select class="style1-select bg-transparent border-0 pl-5">
                                            <option value="">All Categories</option>
                                            <option value="151781441596 ">Chinese History</option>
                                            <option value="139119624252 ">- Pre-historic</option>
                                            <option value="139118313532 ">- Ancient</option>
                                            <option value="139118313532 ">- Imperial</option>
                                            <option value="139360141372 ">Achievement</option>
                                            <option value="139118313532 ">- Mo Di and the School of Names</option>
                                            <option value="139118313532 ">- Four Great Inventions</option>
                                            <option value="139118313532 ">- Scientific and technological stagnation</option>
                                            <option value="152401903676 ">Scholars</option>
                                            <option value="152401903676 ">Allusions and customs</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-lg-3">
                                    <a href="default-search.html" class="w-100 d-block btn bg-current text-white font-xssss fw-600 ls-3 style1-input p-0 border-0 text-uppercase">Search</a>
                                </div>
                            </div>
                        </div>
                        <h4 class="text-grey-500 font-xssss fw-500 ml-1 lh-24"><b class="text-grey-800 text-dark">Popular Search :</b> History of China, Invention, Han dyansty, scholars, arts, poet</h4>
                    </div>
                </div>
            </div>
            <div class="col-lg-12 pt-2 mb-4">
                <h2 class="fw-400 font-lg">
                    Search <b>Results</b> <span class="fw-500 ml-2 text-grey-500 font-xssss">( {{ total_count }} course is found )</span> <a href="#" class="float-right"><i class="feather-edit text-grey-500 font-xs"></i></a>
                </h2>
            </div>

            {% for course in object_list %}
            <div class="col-xl-4 col-xxxl-3 col-lg-6 col-md-6 col-sm-6 mb-4">
                <div class="card course-card w-100 p-0 shadow-xss border-0 rounded-lg overflow-hidden mr-1">
                    <div class="card-image w-100 mb-3">
                        <a href="{% url 'course:details' course.pk %}" class="video-bttn position-relative d-block"><img src="{{ course.photo.url }}" alt="image" class="w-100" /></a>
                    </div>
                    <div class="card-body pt-0">
                        <span class="font-xsssss fw-700 pl-3 pr-3 lh-32 text-uppercase rounded-lg ls-2 alert-warning d-inline-block text-warning mr-1">Python</span>
                        <span class="font-xss fw-700 pl-3 pr-3 ls-2 lh-32 d-inline-block text-success float-right"><span class="font-xsssss">$</span> 240</span>
                        <h4 class="fw-700 font-xss mt-3 lh-28 mt-0"><a href="{% url 'course:details' course.pk %}" class="text-dark text-grey-900">{{ course.title }} </a></h4>
                        <h6 class="font-xssss text-grey-500 fw-600 ml-0 mt-2">32 Lesson</h6>
                        <ul class="memberlist mt-3 mb-2 ml-0 d-block">
                            <li>
                                <a href="#"><img src="{% static 'images/user-6.png' %}" alt="user" class="w30 d-inline-block" /></a>
                            </li>
                            <li>
                                <a href="#"><img src="{% static 'images/user-7.png' %}" alt="user" class="w30 d-inline-block" /></a>
                            </li>
                            <li>
                                <a href="#"><img src="{% static 'images/user-8.png' %}" alt="user" class="w30 d-inline-block" /></a>
                            </li>
                            <li>
                                <a href="#"><img src="{% static 'images/user-3.png' %}" alt="user" class="w30 d-inline-block" /></a>
                            </li>
                            <li class="last-member"><a href="#" class="bg-greylight fw-600 text-grey-500 font-xssss ls-3 text-center">+2</a></li>
                            <li class="pl-4 w-auto"><a href="#" class="fw-500 text-grey-500 font-xssss">Student apply</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            {% endfor %}

            <div class="col-lg-12">
                <ul class="pagination justify-content-center d-flex pt-5">
                    <li class="page-item m-1">
                        <a class="page-link rounded-lg btn-round-md p-0 fw-600 shadow-xss bg-white text-grey-900 border-0" href="#" tabindex="-1" aria-disabled="true"><i class="ti-angle-left"></i></a>
                    </li>
                    <li class="page-item m-1"><a class="page-link rounded-lg btn-round-md p-0 fw-600 font-xssss shadow-xss bg-white text-grey-900 border-0" href="#">1</a></li>
                    <li class="page-item m-1"><a class="page-link rounded-lg btn-round-md p-0 fw-600 font-xssss shadow-xss bg-primary text-white border-0" href="#">2</a></li>
                    <li class="page-item m-1"><a class="page-link rounded-lg btn-round-md p-0 fw-600 font-xssss shadow-xss bg-white text-grey-900 border-0" href="#">3</a></li>
                    <li class="page-item m-1"><a class="page-link rounded-lg btn-round-md p-0 fw-600 font-xssss shadow-xss bg-white text-grey-900 border-0" href="#">4</a></li>
                    <li class="page-item m-1"><a class="page-link rounded-lg btn-round-md p-0 fw-600 font-xssss shadow-xss bg-white text-grey-900 border-0" href="#">5</a></li>
                    <li class="page-item m-1">
                        <a class="page-link rounded-lg btn-round-md p-0 fw-600 shadow-xss bg-white text-grey-900 border-0" href="#"><i class="ti-angle-right"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock content %}