blog/urls.py
from django.urls import path

from blog import views

app_name = "blog"


urlpatterns = [
    path("", views.BlogListView.as_view(), name="list"),
]

cultch/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

from .views import HomePageView, GameView
from .translations import set_language

urlpatterns = [
    path('management/', admin.site.urls),
    path('setlang/', set_language, name='set_language'),
    path('', GameView.as_view(), name='game'),

]

# Language Translation
urlpatterns += i18n_patterns(
    path('', HomePageView.as_view(), name='home'),
    path('user/', include('customauth.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('courses/', include('course.urls')),
    path('blogs/', include('blog.urls')),
    path('virtualtour/', include('virtualtour.urls')),
    path('history/', include('history.urls')),
    path('readclassic/', include('readclassic.urls')),
    path('diago/', include('diago.urls')),
    path('west/', include('west.urls')),

)

# rosetta urls ------------------------------
if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

# serve media files in development environment --------------------------------
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

customauth/urls.py
from django.urls import path

from customauth import views

app_name = 'customauth'


urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('<int:pk>/profile/', views.UserProfileView.as_view(), name='user_profile'),

]

diago/urls.py
from django.urls import path

from course import views
from diago import views

app_name = "diago"


urlpatterns = [
    path("", views.DiagoView.as_view(), name="diago"),

    # path(
    #     '<int:pk>/details/', views.CourseDetailsView.as_view(),
    #     name='details'
    # )
]

history/urls.py
from django.urls import path

from course import views
from history import views

app_name = "history"


urlpatterns = [

    path('dynasty_song/', views.HistoryPagesongsView.as_view(), name="dynasty_song"),
    # path(
    #     '<int:pk>/details/', views.CourseDetailsView.as_view(),
    #     name='details'
    # )
]

west/urls.py
from django.urls import path

from course import views
from west import views

app_name = "west"


urlpatterns = [
    path("", views.WestView.as_view(), name="west"),

    # path(
    #     '<int:pk>/details/', views.CourseDetailsView.as_view(),
    #     name='details'
    # )
]

templates/base/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <title>CULTCH - Exploring Chinese Language & Culture</title>

        <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}" />
        <!-- Favicon icon -->
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon.png' %}" />
        <!-- Custom Stylesheet -->
            <link rel="stylesheet" href="{% static 'css/style.css' %}" />
            <link rel="stylesheet" href="{% static 'css/feather.css' %}" />
            {% block extracss %}
            {% endblock extracss %}
    </head>

    <body class="color-theme-blue mont-font">
        <div class="preloader"></div>

        <div class="main-wrap">
            <!-- header wrapper -->
            {% include "base/wrapper.html" %}
            {% include "base/menu.html" %}

            {% block content %}
            {% endblock content %}

            <!-- footer wrapper -->
            {% include 'base/footer.html' %}
            <!-- footer wrapper -->
        </div>

        <script src="{% static 'js/plugin.js' %}"></script>
        <script src="{% static 'js/aos.min.js' %}"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
        <script>
            AOS.init();
        </script>
        {% block extrajs %}
        {% endblock extrajs %}
    </body>
</html>

templates/base/base_game.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <title>CULTCH - Exploring Chinese Language & Culture</title>

        <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}" />
        <!-- Favicon icon -->
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon.png' %}" />
        <!-- Custom Stylesheet -->
            <link rel="stylesheet" href="{% static 'css/style.css' %}" />
            <link rel="stylesheet" href="{% static 'css/feather.css' %}" />
            {% block extracss %}
            {% endblock extracss %}
    </head>

    <body class="color-theme-blue mont-font">
        <div class="preloader"></div>

        <div class="main-wrap">
            <!-- header wrapper -->
            {% include "base/wrapper.html" %}
            {% include "base/menu.html" %}

            {% block content %}
            {% endblock content %}

            <!-- footer wrapper -->
            {% include 'base/footer_game.html' %}
            <!-- footer wrapper -->
        </div>

        <script src="{% static 'js/plugin.js' %}"></script>
        <script src="{% static 'js/aos.min.js' %}"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
        <script>
            AOS.init();
        </script>
        {% block extrajs %}
        {% endblock extrajs %}
    </body>
</html>

templates/base/base_login.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <title>CULTCH - Exploring Chinese Language & Culture</title>

        <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}" />
        <!-- Favicon icon -->
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon.png' %}" />
        <!-- Custom Stylesheet -->
            <link rel="stylesheet" href="{% static 'css/style.css' %}" />
            <link rel="stylesheet" href="{% static 'css/feather.css' %}" />
            {% block extracss %}
            {% endblock extracss %}
    </head>

    <body class="color-theme-blue mont-font">
        <div class="preloader"></div>

        <div class="main-wrap1">
            <!-- header wrapper -->



            {% block content %}
            {% endblock content %}

            <!-- footer wrapper -->

            <!-- footer wrapper -->
        </div>

        <script src="{% static 'js/plugin.js' %}"></script>
        <script src="{% static 'js/aos.min.js' %}"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
        <script>
            AOS.init();
        </script>
        {% block extrajs %}
        {% endblock extrajs %}
    </body>
</html>

templates/base/footer.html
{% load static i18n %}

<div class="footer-wrapper mt-0 bg-white">
    <div class="container">
        <div class="row">

            <div class="col-sm-12 lower-footer pt-0"></div>
            <div class="col-sm-6 col-xs-12">
                <p class="copyright-text">© {% now 'Y' %} copyright. All rights reserved.</p>
            </div>
            <div class="col-sm-6 col-xs-12 text-right">
                <p class="copyright-text float-right">Design by <a href="#" class="">Teamxxx</a></p>
            </div>
        </div>
    </div>
</div>

templates/base/footer_game.html
{% load static i18n %}

<div class="footer-wrapper mt-0 bg-white" style="padding-top: 40%">
    <div class="container">
        <div class="row">

            <div class="col-sm-12 lower-footer pt-0"></div>
            <div class="col-sm-6 col-xs-12">
                <p class="copyright-text">© {% now 'Y' %} copyright. All rights reserved.</p>
            </div>
            <div class="col-sm-6 col-xs-12 text-right">
                <p class="copyright-text float-right">Design by <a href="#" class="">Teamxxx</a></p>
            </div>
        </div>
    </div>
</div>

templates/base/menu.html
{% load static i18n %}

<div class="header-wrapper pt-3 pb-3 shadow-none">
    <div class="container">
        <div class="row">
            <div class="col-lg-9 navbar pt-0 pb-0">
                <a href="{% url 'home' %}">
                    <h1 class="fredoka-font ls-3 fw-700 text-current font-xxl">CULTCH <span class="d-block font-xsssss ls-1 text-grey-500 open-font">Explore Chinese Language & Culture</span></h1>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown" >
                    <ul class="navbar-nav nav-menu float-none text-center">
                        <li class="nav-item"><a class="nav-link" href="{% url 'home' %}">{% translate 'Home' %}</a></li>
                        <li class="nav-item"><a class="nav-link" href="#">{% translate 'Travel Through Millennium' %}</a>
                        <ul class="ur_st">
                        <li class="nav-item"><a class="nav-link" href="{% url 'history:dynasty_song'%}">{% translate 'Dynasty Songs' %}</a></li><br>
                        <li class="nav-item"><a class="nav-link" href="{% url 'game'%}">{% translate 'A Funny Game' %}</a></li>
                        </ul>

                          <li class="nav-item"><a class="nav-link" href="#">{% translate 'Immersive' %}</a>
                        <ul class="ur_st2">
                       <li class="nav-item"><a class="nav-link" href="{% url 'vt:list' %}">{% translate 'Virtual Tours' %}</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'vt:sharevideo'%}">{% translate 'Trip Videos' %}</a></li>
                        </ul>

                        <li class="nav-item"><a class="nav-link" href="#">{% translate 'Read Classics' %}</a>
                        <ul class="ur_st2">
                       <li class="nav-item"><a class="nav-link" href="{% url 'readclassic:lfs' %}">{% translate 'Famous Sayings' %}</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'readclassic:cs' user.email %}">{% translate 'Classic Sharing' %}</a></li>
                        </ul>
                        <li class="nav-item"><a class="nav-link" href="{% url 'diago:diago' %}">{% translate 'Dialogue with sages' %}</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'west:west' %}">{% translate 'East to West' %}</a></li>

{#                        <li class="nav-item"><a class="nav-link" href="contact.html">{% translate 'Contact' %}</a></li>#}
                    </ul>
                </div>
            </div>
            <div class="col-lg-3 text-right d-none d-lg-block">
                <a href="{% url 'customauth:login' %}" class="header-btn bg-dark fw-500 text-white font-xssss p-2 lh-32 w100 text-center d-inline-block rounded-xl mt-1">{% translate 'Login' %}</a>
                <a href="{% url 'customauth:register' %}" class="header-btn bg-current fw-500 text-white font-xssss p-2 lh-32 w100 text-center d-inline-block rounded-xl mt-1">{% translate 'Register' %}</a>
            </div>
        </div>
    </div>
</div>
<style>
ul li{
    list-style: none;
}


.ur_st{
    width: 16%;
    height: 10%;
    margin-left: 1%;
    background-color: #FFFFFF;
    display: none;
    position: absolute;
    z-index: 50;
}
.ur_st2{
    width: 20%;
    height: 10%;
    margin-left: 0%;
    background-color: #FFFFFF;
    display: none;
    position: absolute;
    z-index: 50;
}
#navbarNavDropdown li:hover ul{
    display: block;
}
</style>

templates/base/wrapper.html
{% load humanize static i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}

<div class="upper-header bg-greylight">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-xs-6 d-none d-block-md">
                <ul class="list-inline list-item-style mt-0 float-left pl-1">
                    <li class="list-inline-item pl-0"><a href="#">(+1)866-540-3229</a></li>
                </ul>
            </div>
            <div class="col-md-6 col-xs-6 d-none d-block-md">
                <ul class="list-inline list-item-style mt-0 float-right">
                    <li class="list-inline-item">
                        <a href="#"><i class="ti-user mr-2"></i> {% translate 'My Account' %}</a>
                    </li>
                </ul>
            </div>
            <div class="col-12 d-none d-lg-block">
                <ul class="list-inline list-item-style mt-0 float-left pl-1">
                    <li class="list-inline-item pl-0"><a href="#">{% translate 'TERMS OF USE' %}</a></li>
                    <li class="list-inline-item"><a href="#">{% translate 'PRIVACY POLICY' %}</a></li>
                </ul>

                <ul class="list-inline list-item-style mt-0 float-right">
                    <li class="list-inline-item">
                        <div class="form-group">
                            {% get_current_language as LANGUAGE_CODE %}
                            {% get_available_languages as LANGUAGES %}
                            {% get_language_info_list for LANGUAGES as languages %}
                            <a href="{% url 'set_language' %}?language={{ languages.0.code }}">English</a>
                            <a href="{% url 'set_language' %}?language={{ languages.1.code }}">中文</a>
                        </div>
                    </li>
                    <li class="list-inline-item">
                        <a href="#"><i class="ti-location-pin mr-2"></i> {% translate 'China' %}</a>
                    </li>
                    <li class="list-inline-item">
                                  {% if user.is_authenticated %}
                      <em><i class="ti-user mr-2"></i> {{ user.email }}</em>
                                  {% else %}       <span class="list-inline-item pl-0"> {% translate 'Please Login' %}</span>
                {% endif %}
                    </li>
                </ul>
            </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>